import React, { useRef, useEffect } from 'react';
import Button from './ui/Button';

export default function Hero() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const videoSources = [
    '/VIDEO/1.mp4',
    '/VIDEO/2.mp4',
    '/VIDEO/3.mp4',
    '/VIDEO/4.mp4',
    '/VIDEO/5.mp4',
    '/VIDEO/6.mp4',
    '/VIDEO/7.mp4',
  ];

  useEffect(() => {
    const videoElement = videoRef.current;
    let currentVideoIndex = 0;

    const handleVideoEnd = () => {
      currentVideoIndex = (currentVideoIndex + 1) % videoSources.length;
      if (videoElement) {
        videoElement.src = videoSources[currentVideoIndex];
        videoElement.play();
      }
    };

    if (videoElement) {
      videoElement.addEventListener('ended', handleVideoEnd);
    }

    return () => {
      if (videoElement) {
        videoElement.removeEventListener('ended', handleVideoEnd);
      }
    };
  }, [videoSources]);

  return (
    <div className="relative min-h-screen flex items-center">
      {/* Background with video */}
      <div className="absolute inset-0 overflow-hidden">
        <video
          ref={videoRef}
          className="w-full h-full object-cover scale-110"
          autoPlay
          muted
          playsInline
        >
          <source src={videoSources[0]} type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <div className="absolute inset-0 bg-black/70"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="space-y-8">
          <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-white leading-tight">
            Enhancing <span className="animate-gradient bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 via-indigo-500 to-purple-500 bg-[size:200%] text-transparent bg-clip-text">Human Capability</span> for the <span className="animate-gradient bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 via-indigo-500 to-purple-500 bg-[size:200%] text-transparent bg-clip-text">Next Leap</span>
          </h1>
          
          <p className="text-xl text-gray-300 max-w-2xl">
            We believe the next great leap in human evolution will come from the conscious enhancement of our cognitive, educational, and medical capabilities — through rigorous research, open tools, and responsible translation.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4">
            <Button 
              href="/projects" 
              variant="primary" 
              icon
              className="transform transition-transform duration-300 hover:scale-105 hover:shadow-lg hover:shadow-blue-500/50"
            >
              Explore Projects
            </Button>
            <Button 
              href="/contact" 
              variant="secondary"
              className="transform transition-transform duration-300 hover:scale-105 hover:shadow-lg hover:shadow-indigo-500/50"
            >
              Contact Us
            </Button>
          </div>
        </div>
      </div>
      <p className="absolute bottom-2 left-1/2 transform -translate-x-1/2 text-sm text-gray-400 z-20">
        Images by OdysseyXL. Videos generated by Mochi 1.
      </p>
    </div>
  );
}
